// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Account, error)
	DeleteAccount(ctx context.Context, id int64) error
	GetAuthor(ctx context.Context, id int64) (Account, error)
	ListAuthors(ctx context.Context, arg ListAuthorsParams) ([]Account, error)
	UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) error
}

var _ Querier = (*Queries)(nil)
